/* generated by src/pages/sw.js.js — do not edit in dist/ */
const V = "590426364f36";
const SHELL_CACHE = "stops-shell-" + V;
const RUN_CACHE = "stops-run-" + V;
const BASE = "/shanghai-stops/";
const OFFLINE = "/shanghai-stops/offline";
const SHELL = ["/shanghai-stops/","/shanghai-stops/places","/shanghai-stops/routes","/shanghai-stops/guides","/shanghai-stops/how-i-score","/shanghai-stops/about","/shanghai-stops/offline","/shanghai-stops/fonts/anton-v1.woff2","/shanghai-stops/favicon.svg","/shanghai-stops/apple-touch-icon.png","/shanghai-stops/manifest.webmanifest"];

/* Never cached. The tile archive is nineteen megabytes and is read with range
   requests, and MapLibre is two more — putting either in a cache would spend
   a reader's foreign data on something they did not ask for. The map page
   itself caches like any other document; only its payload is excluded. */
const skip = (p) =>
  p.endsWith(".pmtiles") || /\/map\/(lib|fonts)\//.test(p) || p.includes("/api/");

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    /* One at a time. addAll rejects the whole install if a single URL 404s,
       and an install that fails leaves the reader with no worker at all. */
    await Promise.all(SHELL.map((url) =>
      cache.add(new Request(url, { cache: "reload" })).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith("stops-") && !key.endsWith(V)) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (!url.pathname.startsWith(BASE)) return;
  if (skip(url.pathname)) return;

  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: true });
    /* Refresh in the background whether or not there was a hit, so a page
       read underground is the one from the last time there was signal. */
    const fresh = fetch(req).then(async (res) => {
      if (res && res.ok && res.type === "basic") {
        const cache = await caches.open(RUN_CACHE);
        cache.put(req, res.clone());
      }
      return res;
    }).catch(() => null);

    if (hit) return hit;
    const res = await fresh;
    if (res) return res;
    /* No cache, no network. A document gets the page that explains that; an
       image or a stylesheet gets nothing, which is what a browser expects. */
    if (req.mode === "navigate") {
      return (await caches.match(OFFLINE)) ??
        new Response("Offline, and this page was never opened on this device.",
          { status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } });
    }
    return Response.error();
  })());
});
